name: CI - build & test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Gotorz/Gotorz.sln

    - name: Build solution
      run: dotnet build Gotorz/Gotorz.sln --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test Gotorz/Gotorz.sln --configuration Release --no-build --verbosity normal

    - name: Publish Blazor Web App
      run: dotnet publish Gotorz/Gotorz.csproj \
            --configuration Release \
            --output ./publish \
            --no-build

    - name: Upload Published Artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: publish